### ISSUE TITLE
Overrides the whole TCA of one of our models

### ISSUE THREAD

**Issue by lia-devs** [CodersCare/l10nmgr#4]
After installing the alpha version (11.0.0) of the extension, one of my TCA configurations was completely overwritten.
This TCA now has no information about the columns, palettes or controls. It contains only one entry sourceLangStaticId.
I searched for the field and found it in your extension.
I thought it might be related to the loading order and packed the extension far up in the Suggest, but unfortunately that didn't help.

**Comment by Bunnyfield** [comment]
If you want to use a version with CMS 11 please do not use the current master, since it is not supposed to actually run with the latest TYPO3 LTS version.

There is a working version though, which is available wihtin a private repository for sponsors, which you can get access to by supporting our crowdfunding campaign:

https://coders.care/for/crowdfunding/l10nmgr-and-localizer/support
