### ISSUE TITLE
IDs not matching while importing translated .xml (TYPO3 v12)

### ISSUE THREAD

**Issue by twaurisch** [CodersCare/l10nmgr#45]
Hello, we are using the EAP version for TYPO3 v12 and are confused because of the behavior during the import of an .xml.

### The scenario

A page with content only in the default language should be translated, the export works.

During the import of the translated .xml:

- the new page with sys_language_uid = 1 is being created, translated dates is being used
- language id 1 content records are created, as a copy of the default language
- now the content from the .xml should be transfered into the newly created content records with language id 1
- BUT during this step the field IDs in the .xml are IDs from the default language and they get compared with the field IDs from the new language version. Due to the no match condition the fields won't be imported.

### A short example

`tt_content:NEW/5/13:bodytext` - Field ID in the XML, where `13` is the `tt_content.uid` of the default language.

In the `L10nBaseService->_submitContentAsTranslatedLanguageAndGetFlexFormDiff()` method this Field ID is compared to
`tt_content:18:bodytext` which the newly created and has the language id 1. `tt_content:NEW/5/13:bodytext` stays in the $inputArray because was not processed.

At the end the debug() function shows, which fields weren't imported.

**Comment by Bunnyfield** [comment]
Hi Thomas.

Since this about the EA version 12, could you please report issues in the bugtracker of the EA repository?

Having a short look at your description the problem seems to be the language ID, not the element ID.
The XML file provides translations for language ID 5 - the one directly after NEW - while the new page gets created with language ID 1. So my guess would be that the export was targeted to another language but then translated to the wrong language.

A simple search and replace from NEW/5 to NEW/1 should help in this case.

**Comment by twaurisch** [comment]
Thank for your fast feedback. I'm sorry, I mixed up the language ids in my example. All is related to sys_language_uid = 5. I'll fix it up there. 

Next to this I need to check who has the EA repo access in our company.
